spring.application.name=class-booking-service

server.port=8082

# Base de datos de reservas de clases
spring.datasource.url=jdbc:postgresql://localhost:5434/gym_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8280/realms/gym-system
